#!/usr/bin/env python3
"""Build official PDF Unicode mapping tables.

Sources (see data/):
  - Unicode EquivalentUnifiedIdeograph (UAX #44)
  - Unicode NFKC on CJK compatibility blocks
  - Adobe pdf2unicode CID → UCS2 CMaps (GB1/CNS1/Japan1/Korea1/KR)
  - Adobe Glyph List + ZapfDingbats
  - PDF standard encodings (ISO 32000 Annex D), via glyph names

Do not edit src/generated/* by hand. Re-run:

  python3 packages/pdf/scripts/gen-maps.py
"""

from __future__ import annotations

import json
import re
import struct
import unicodedata
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
OUT = ROOT / "src" / "generated"

HEADER = """\
// Generated by scripts/gen-maps.py. Do not edit.
// Official Unicode / Adobe / ISO 32000 mapping tables for PDF text extraction.
"""


def parse_equiv(text: str) -> dict[int, int]:
    out: dict[int, int] = {}
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or line.startswith("@") or ";" not in line:
            continue
        src, dst = [p.strip() for p in line.split(";", 1)]
        dest = int(dst, 16)
        if ".." in src:
            a, b = src.split("..", 1)
            start, end = int(a, 16), int(b, 16)
        else:
            start = end = int(src, 16)
        for cp in range(start, end + 1):
            out[cp] = dest
    return out


def add_nfkc_block(table: dict[int, int], start: int, end: int) -> None:
    for cp in range(start, end + 1):
        if cp in table:
            continue
        ch = chr(cp)
        nk = unicodedata.normalize("NFKC", ch)
        if nk != ch and len(nk) == 1:
            table[cp] = ord(nk)


def parse_agl(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        if not raw or raw.startswith("#") or ";" not in raw:
            continue
        name, hexv = raw.split(";", 1)
        hexv = hexv.strip()
        chars: list[str] = []
        for part in hexv.split():
            chars.append(chr(int(part, 16)))
        out[name.strip()] = "".join(chars)
    return out


def hex_to_cp(h: str) -> int:
    hx = re.sub(r"[^0-9a-fA-F]", "", h)
    if len(hx) % 2 == 1:
        hx += "0"
    bs = bytes.fromhex(hx) if hx else b""
    if len(bs) >= 4:
        a = int.from_bytes(bs[0:2], "big")
        b = int.from_bytes(bs[2:4], "big")
        if 0xD800 <= a <= 0xDBFF and 0xDC00 <= b <= 0xDFFF:
            return 0x10000 + ((a - 0xD800) << 10) + (b - 0xDC00)
    if len(bs) >= 2:
        return int.from_bytes(bs[0:2], "big")
    return int(hx, 16) if hx else 0


def parse_to_unicode_cmap(text: str) -> dict[int, int]:
    cmap: dict[int, int] = {}

    def hexint(h: str) -> int:
        return int(re.sub(r"[^0-9a-fA-F]", "", h), 16)

    pos = 0
    while True:
        start = text.find("beginbfchar", pos)
        if start < 0:
            break
        end = text.find("endbfchar", start)
        if end < 0:
            break
        toks = re.findall(r"<([^>]*)>", text[start + 11 : end])
        for i in range(0, len(toks) - 1, 2):
            cmap[hexint(toks[i])] = hex_to_cp(toks[i + 1])
        pos = end + 9

    pos = 0
    while True:
        start = text.find("beginbfrange", pos)
        if start < 0:
            break
        end = text.find("endbfrange", start)
        if end < 0:
            break
        section = text[start + 12 : end]
        for m in re.finditer(
            r"<([^>]*)>\s*<([^>]*)>\s*(?:<([^>]*)>|\[((?:<[^>]*>\s*)+)\])",
            section,
        ):
            a = hexint(m.group(1))
            b = hexint(m.group(2))
            if m.group(3) is not None:
                base = hex_to_cp(m.group(3))
                for cid in range(a, b + 1):
                    cmap[cid] = base + (cid - a)
            else:
                dests = re.findall(r"<([^>]*)>", m.group(4))
                for i, dest in enumerate(dests):
                    if a + i <= b:
                        cmap[a + i] = hex_to_cp(dest)
        pos = end + 10
    return cmap


def pack_flat_u16(cmap: dict[int, int]) -> tuple[bytes, list[tuple[int, int]]]:
    max_cid = max(cmap) if cmap else 0
    flat = bytearray((max_cid + 1) * 2)
    extra: list[tuple[int, int]] = []
    for cid, cp in cmap.items():
        if 1 <= cp <= 0xFFFF:
            flat[cid * 2] = cp & 0xFF
            flat[cid * 2 + 1] = (cp >> 8) & 0xFF
        elif cp > 0xFFFF:
            extra.append((cid, cp))
    return bytes(flat), extra


def b64(data: bytes) -> str:
    import base64

    return base64.b64encode(data).decode("ascii")


def parse_encodings_js(text: str) -> dict[str, list[str]]:
    out: dict[str, list[str]] = {}
    for m in re.finditer(r"const (\w+Encoding) = \[([\s\S]*?)\];", text):
        names: list[str] = []
        for tok in re.findall(r'"([^"]*)"', m.group(2)):
            names.append(tok)
        # pad / trim to 256
        if len(names) < 256:
            names.extend([""] * (256 - len(names)))
        out[m.group(1)] = names[:256]
    return out


def pack_cjk(table: dict[int, int]) -> bytes:
    items = sorted(table.items())
    out = bytearray(struct.pack("<I", len(items)))
    for src, dst in items:
        out += struct.pack("<II", src, dst)
    return bytes(out)


def pack_adobe(maps: dict[str, dict[int, int]]) -> bytes:
    out = bytearray(struct.pack("<B", len(maps)))
    for key, cmap in maps.items():
        flat, extra = pack_flat_u16(cmap)
        kb = key.encode("ascii")
        out += struct.pack("<B", len(kb)) + kb
        out += struct.pack("<I", len(flat)) + flat
        out += struct.pack("<H", len(extra))
        for cid, cp in extra:
            out += struct.pack("<HI", cid, cp)
        print(f"adobe-cid {key}: {len(cmap)} mappings, flat {len(flat)}B, extra {len(extra)}")
    return bytes(out)


def pack_agl(agl: dict[str, str]) -> bytes:
    lines: list[str] = []
    for name, value in sorted(agl.items()):
        hexes = " ".join(f"{ord(ch):04X}" for ch in value)
        lines.append(f"{name}\t{hexes}")
    return "\n".join(lines).encode("utf-8")


def pack_encoding_cmaps(packed: dict[str, dict], uni: dict[str, str]) -> bytes:
    names = list(packed)
    idx = {n: i for i, n in enumerate(names)}
    out = bytearray()
    name_blob = "\0".join(names).encode("ascii")
    out += struct.pack("<HH", len(names), len(name_blob))
    out += name_blob
    uni_blob = "\0".join(f"{k}={v}" for k, v in uni.items()).encode("ascii")
    out += struct.pack("<HH", len(uni), len(uni_blob))
    out += uni_blob
    for name in names:
        entry = packed[name]
        base = entry.get("b")
        space = entry.get("s") or []
        ranges = entry.get("r") or []
        flags = 1 if base else 0
        out += struct.pack("<B", flags)
        if base:
            if base not in idx:
                raise SystemExit(f"usecmap {base} missing for {name}")
            out += struct.pack("<H", idx[base])
        out += struct.pack("<H", len(space) // 3)
        for i in range(0, len(space), 3):
            out += struct.pack("<IIB", space[i], space[i + 1], space[i + 2])
        out += struct.pack("<I", len(ranges) // 3)
        for i in range(0, len(ranges), 3):
            cid = ranges[i + 2]
            if cid < 0 or cid > 0xFFFF:
                raise SystemExit(f"cid overflow {name} {cid}")
            out += struct.pack("<IIH", ranges[i], ranges[i + 1], cid)
    return bytes(out)


def write_maps_bin(
    equiv: dict[int, int],
    adobe: dict[str, dict[int, int]],
    agl: dict[str, str],
    enc_packed: dict[str, dict],
    uni: dict[str, str],
) -> None:
    sections = [
        (b"CJK1", pack_cjk(equiv)),
        (b"CID1", pack_adobe(adobe)),
        (b"AGL1", pack_agl(agl)),
        (b"ENC1", pack_encoding_cmaps(enc_packed, uni)),
    ]
    raw = bytearray(b"MDG1")
    for tag, payload in sections:
        raw += tag + struct.pack("<I", len(payload)) + payload
    blob = zlib.compress(bytes(raw), 9)
    path = OUT / "maps.bin"
    path.write_bytes(blob)
    print(
        f"maps.bin: {len(blob)}B zlib / {len(raw)}B raw "
        f"(was ~635KB of base64 inside index.js)"
    )
    for stale in (
        "adobe-cid-data.ts",
        "encoding-cmap-data.ts",
        "glyphlist-data.ts",
        "cjk-equiv.ts",
    ):
        p = OUT / stale
        if p.exists():
            p.unlink()
            print(f"removed {stale}")


def write_encodings(encodings: dict[str, list[str]], agl: dict[str, str]) -> None:
    # Resolve names to a 256-char table. Unmapped slots are U+0000.
    chunks = [HEADER, "export const PDF_ENCODINGS: Record<string, string> = {"]
    alias = {
        "WinAnsiEncoding": "WinAnsiEncoding",
        "MacRomanEncoding": "MacRomanEncoding",
        "StandardEncoding": "StandardEncoding",
        "MacExpertEncoding": "MacExpertEncoding",
        "ExpertEncoding": "ExpertEncoding",
        "SymbolSetEncoding": "SymbolEncoding",
        "ZapfDingbatsEncoding": "ZapfDingbatsEncoding",
    }
    seen: set[str] = set()
    for js_name, names in encodings.items():
        pdf_name = alias.get(js_name, js_name)
        if pdf_name in seen:
            continue
        seen.add(pdf_name)
        chars: list[str] = []
        for name in names:
            if not name:
                chars.append("\0")
                continue
            mapped = agl.get(name)
            chars.append(mapped if mapped else "\0")
        table = "".join(chars)
        if len(table) != 256:
            raise SystemExit(f"{pdf_name} resolved to {len(table)} chars")
        chunks.append(f"  {json.dumps(pdf_name)}: {json.dumps(table)},")
        mapped_n = sum(1 for c in table if c != "\0")
        print(f"encoding {pdf_name}: {mapped_n}/256 mapped")
    chunks.append("};\n")
    (OUT / "encodings-data.ts").write_text("\n".join(chunks))


def write_glyphlist(agl: dict[str, str]) -> None:
    # Compact "name\\tcp\\n" records. Multi-char values use space-separated hex.
    lines: list[str] = []
    for name, value in sorted(agl.items()):
        hexes = " ".join(f"{ord(ch):04X}" for ch in value)
        lines.append(f"{name}\t{hexes}")
    payload = "\n".join(lines)
    z = zlib.compress(payload.encode("utf-8"), 9)
    body = (
        HEADER
        + f"export const GLYPHLIST_ZLIB = {json.dumps(b64(z))};\n"
    )
    (OUT / "glyphlist-data.ts").write_text(body)
    print(f"glyphlist: {len(agl)} names, zlib {len(z)}B")


def hex_code(h: str) -> int:
    hx = re.sub(r"[^0-9a-fA-F]", "", h)
    return int(hx, 16) if hx else 0


def parse_encoding_cmap(text: str) -> dict:
    name = None
    m = re.search(r"/CMapName\s*/(\S+)\s+def", text)
    if m:
        name = m.group(1)
    usecmap = None
    m = re.search(r"/(\S+)\s+usecmap", text)
    if m:
        usecmap = m.group(1)
    space: list[int] = []
    cs = re.search(r"begincodespacerange(.*?)endcodespacerange", text, re.S)
    if cs:
        for a, b in re.findall(r"<([^>]*)>\s*<([^>]*)>", cs.group(1)):
            lo, hi = hex_code(a), hex_code(b)
            n = max(1, (len(re.sub(r"[^0-9a-fA-F]", "", a)) + 1) // 2)
            space.extend([lo, hi, n])
    ranges: list[int] = []
    pos = 0
    while True:
        start = text.find("begincidrange", pos)
        if start < 0:
            break
        end = text.find("endcidrange", start)
        if end < 0:
            break
        for a, b, cid in re.findall(r"<([^>]*)>\s*<([^>]*)>\s*(-?\d+)", text[start:end]):
            ranges.extend([hex_code(a), hex_code(b), int(cid)])
        pos = end + 11
    pos = 0
    while True:
        start = text.find("begincidchar", pos)
        if start < 0:
            break
        end = text.find("endcidchar", start)
        if end < 0:
            break
        for a, cid in re.findall(r"<([^>]*)>\s*(-?\d+)", text[start:end]):
            code = hex_code(a)
            ranges.extend([code, code, int(cid)])
        pos = end + 10
    return {"name": name, "base": usecmap, "s": space, "r": ranges}


def collect_encoding_cmaps() -> tuple[dict[str, dict], dict[str, str]]:
    cmap_dir = DATA / "cmaps"
    packed: dict[str, dict] = {}
    for path in sorted(cmap_dir.iterdir()):
        if not path.is_file():
            continue
        parsed = parse_encoding_cmap(path.read_text(encoding="latin1"))
        name = parsed["name"] or path.name
        entry: dict = {}
        if parsed["base"]:
            entry["b"] = parsed["base"]
        if parsed["s"]:
            entry["s"] = parsed["s"]
        if parsed["r"]:
            entry["r"] = parsed["r"]
        packed[name] = entry

    uni: dict[str, str] = {}
    for stem in (
        "UniGB",
        "UniCNS",
        "UniJIS",
        "UniJIS2004",
        "UniJISPro",
        "UniJISX0213",
        "UniJISX02132004",
        "UniKS",
        "UniAKR",
    ):
        for enc, kind in (
            ("UCS2", "utf16"),
            ("UTF16", "utf16"),
            ("UTF32", "utf32"),
            ("UTF8", "utf8"),
        ):
            for tail in ("-H", "-V", "-HW-H", "-HW-V"):
                uni[f"{stem}-{enc}{tail}"] = kind
    print(f"encoding-cmaps: {len(packed)} legacy, {len(uni)} uni names")
    return packed, uni


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)

    equiv = parse_equiv((DATA / "EquivalentUnifiedIdeograph.txt").read_text(encoding="utf-8"))
    # Complete official lookalike set, not a hand-picked subset.
    add_nfkc_block(equiv, 0x2F00, 0x2FD5)  # Kangxi (also in Equiv file; NFKC is identical)
    add_nfkc_block(equiv, 0xF900, 0xFAFF)  # CJK Compatibility Ideographs
    add_nfkc_block(equiv, 0x2F800, 0x2FA1F)  # Compatibility Ideographs Supplement
    add_nfkc_block(equiv, 0xFE30, 0xFE4F)  # CJK Compatibility Forms (vertical)

    agl = parse_agl(DATA / "glyphlist.txt")
    agl.update(parse_agl(DATA / "zapfdingbats.txt"))

    encodings = parse_encodings_js((DATA / "encodings.js").read_text(encoding="utf-8"))
    write_encodings(encodings, agl)

    adobe = {
        "GB1": parse_to_unicode_cmap((DATA / "Adobe-GB1-UCS2").read_text(encoding="latin1")),
        "CNS1": parse_to_unicode_cmap((DATA / "Adobe-CNS1-UCS2").read_text(encoding="latin1")),
        "Japan1": parse_to_unicode_cmap((DATA / "Adobe-Japan1-UCS2").read_text(encoding="latin1")),
        "Korea1": parse_to_unicode_cmap((DATA / "Adobe-Korea1-UCS2").read_text(encoding="latin1")),
        "KR": parse_to_unicode_cmap((DATA / "Adobe-KR-UCS2").read_text(encoding="latin1")),
    }
    enc_packed, uni = collect_encoding_cmaps()
    write_maps_bin(equiv, adobe, agl, enc_packed, uni)


if __name__ == "__main__":
    main()
